apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ivanms1/backend-task
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-example
    spec:
      containers:
      - name: backend-task
        image: ivanms1/backend-task
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"