apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  version: 9
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    scriptSource:
      gitRepo:
        repository: "https://github.com/ivanms1/backend-task-13.git"
        directory: "./init"